website/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [

    # /music/
    url(r'^$', views.index, name='index'),

    #/music/712<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),

    #/music/712<album_id>/favourite
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/Videos/models.py
from django.db import models

# Create your models here.

website/music/models.py
# blueprint of the database
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000) #URL of logo

    def __str__(self):
        return self.album_title+'-'+self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=15)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/Videos/views.py
from django.shortcuts import render

# Create your views here.

website/music/views.py
#from django.http import HttpResponse, Http404
#from django.template import loader	
from .models import Album, Song
from django.shortcuts import render, get_object_or_404


def index(request):
	all_albums = Album.objects.all() #extracting the database
	#template = loader.get_template('music/index.html')
	html_pass = {'all_albums' : all_albums}
	return render(request, 'music/index.html', html_pass)


def details(request, album_id):
	#try:
		#album = Album.objects.get(pk=album_id)
	#except Album.DoesNotExist:
		#raise Http404("Fu*k You,, Album doesn't exist") #raising a 404 error if id not found
	#using shortcut
	album = get_object_or_404(Album, pk = album_id)
	return render(request, 'music/details.html', {'album': album})

def favourite(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	try:
		selected_song = album.song_set.get(pk=request.POST['song'])
	except (KeyError, song.DoesNotExist):
		return render(request, 'music/details.html',
					  {
						  'album' : album,
						  'error_mesage' : "You didn not select a valid song",
					  })
	else:
		selected_song.is_favourite = True
		selected_song.save()
		return render(request, 'music/details.html', {'album': album})

website/music/templates/music/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>
<img src="{{ album.album_logo }}" height="20%" width="22.5%">
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
 <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'music:favourite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
    <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favourite %}
        <img src="http://i.imgur.com/b9b13Rd.png">
        {% endif %}
    </label><br>
    {% endfor %}
    <input type="submit", value="Favourite">
</form>


</body>
</html>

<!--<ul>
    {% for song in album.song_set.all %}
        <li>{{song.song_title}}.{{song.file_type}}</li>
    {% endfor %}
</ul>-->

website/music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Albums page</title>
    <style>
        body {
            font-size: 20px;
        }
    </style>
</head>
<body>
    {% if all_albums %}
        <h3>Here are all my Albums</h3>
        <ul>
            {% for album in all_albums %}
                <!--/*<li><a href="/music/{{album.id}}">{{album.album_title}}</a></li> "hardcoded"-->
                <li><a href="{% url 'music:details' album.id %}">{{album.album_title}}</a></li><!--dynamic-->
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}
</body>
</html>